# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vinit Soni
email: vinitsoni357@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, it's me, Vinit. This is my website, and here, feel free to explore
  and discover more about me!
baseurl: "/cybervinit.github.io/" # the subpath of your site, e.g. /blog
url: "http://cybervinit.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  cybervinit

# Build settings
markdown: kramdown
